'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VotingSystem2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _278316421_1345431755972377_3506599790199463046_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("278316421_1345431755972377_3506599790199463046_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _278316421_1345431755972377_3506599790199463046_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("278316421_1345431755972377_3506599790199463046_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _369835609_228513486754280_8563557307901940175_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("369835609_228513486754280_8563557307901940175_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _369835609_228513486754280_8563557307901940175_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("369835609_228513486754280_8563557307901940175_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _370200949_1516721162500855_3951081349409680349_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("370200949_1516721162500855_3951081349409680349_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _370200949_1516721162500855_3951081349409680349_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("370200949_1516721162500855_3951081349409680349_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _370240539_6844195278968022_1039924469292493529_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("370240539_6844195278968022_1039924469292493529_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _370240539_6844195278968022_1039924469292493529_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("370240539_6844195278968022_1039924469292493529_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _370247249_726566449379432_2478517012325524793_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("370247249_726566449379432_2478517012325524793_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _370247249_726566449379432_2478517012325524793_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("370247249_726566449379432_2478517012325524793_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _370254679_1658373984654542_3633950718521355458_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("370254679_1658373984654542_3633950718521355458_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _370254679_1658373984654542_3633950718521355458_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("370254679_1658373984654542_3633950718521355458_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _370254702_353862957014337_8653972224941656041_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("370254702_353862957014337_8653972224941656041_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _370254702_353862957014337_8653972224941656041_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("370254702_353862957014337_8653972224941656041_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _370338780_6745821252120668_1779365252519710157_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("370338780_6745821252120668_1779365252519710157_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _370338780_6745821252120668_1779365252519710157_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("370338780_6745821252120668_1779365252519710157_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _371321261_319842550404084_1348851786641713069_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("371321261_319842550404084_1348851786641713069_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _371321261_319842550404084_1348851786641713069_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("371321261_319842550404084_1348851786641713069_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _372660634_352447707302437_197117644275120080_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("372660634_352447707302437_197117644275120080_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _372660634_352447707302437_197117644275120080_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("372660634_352447707302437_197117644275120080_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _376599791_1003282050784105_6124692871541218200_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("376599791_1003282050784105_6124692871541218200_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _376599791_1003282050784105_6124692871541218200_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("376599791_1003282050784105_6124692871541218200_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _377208418_325488903521288_7748365072199842937_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("377208418_325488903521288_7748365072199842937_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _377208418_325488903521288_7748365072199842937_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("377208418_325488903521288_7748365072199842937_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _386564286_6716917915058526_4611985100217023698_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("386564286_6716917915058526_4611985100217023698_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _386564286_6716917915058526_4611985100217023698_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("386564286_6716917915058526_4611985100217023698_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _387323675_876500764105193_6687473140912219552_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("387323675_876500764105193_6687473140912219552_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _387323675_876500764105193_6687473140912219552_n1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("387323675_876500764105193_6687473140912219552_n1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_progress_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-progress-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screenshot_2023_11_08_172620() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screenshot 2023-11-08 172620", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screenshot_2023_11_08_1726201() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screenshot 2023-11-08 1726201", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screenshot_2023_11_08_172809() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screenshot 2023-11-08 172809", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screenshot_2023_11_08_1728091() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screenshot 2023-11-08 1728091", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screenshot_2023_11_08_173237() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screenshot 2023-11-08 173237", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Screenshot_2023_11_08_1732371() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Screenshot 2023-11-08 1732371", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property taguig_city_university_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taguig-city-university-logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
